name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/docker-login@v1
      with:
        login-server: jnaeder324test.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build the Docker image
      run: docker build -t jnaeder324test.azurecr.io/jamf-inventory:latest .

    - name: Push Docker image
      run: docker push jnaeder324test.azurecr.io/jamf-inventory:latest

    - name: Create Azure Task
      run: | 
        az acr task create \
        --name jamf-inventory-schedule \
        --registry jnaeder324test \
        --cmd jnaeder324test.azurecr.io/jamf-inventory:latest \
        --schedule "0 21 * * *" \
        --context /dev/null
